baseURL = "https://acep-uaf.github.io/the-arctic-program/"
languageCode = 'en-us'
title = 'The ARCTIC Program'
theme = 'piko'
paginate = "6"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[security.funcs]
getenv = ['^HUGO_', '^CI$']

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true

[minify.tdewolff.html]
keepWhitespace = false

[params]
mapbox_access_token = ""
env = "production"
author = ""
description = "Your website description"
math = false
images = [ "/uploads/og.webp" ]
comments = true
mainSections = [ "blog" ]
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowRelated = true
CookieNotice = "We use cookies to improve your experience on our site and to show you relevant advertising."
CookieLink = "/legal/privacy/#cookies-and-web-beacons"
CookieButton = "Cookies Policy"
disableAnchoredHeadings = false
ShowReadingTime = false
ShowBreadCrumbs = true
showTOC = false
contactEmail = "UA-arctic-program-contact@alaska.edu"
footerAcknowledgement = "Website Management by [UAF ACEP](https://www.uaf.edu/acep/). Website template by [Heksagon](https://github.com/heksagonnet/piko)"
relativeURLs = true


[params.analytics.google]

[params.analytics.yandex]

[params.analytics.bing]

  [params.label]
  title = "_ARCTIC Program_"
  text = "Welcome to the ARCTIC Program"
  lightNavIcon = "images/favicon.png"
  darkNavIcon = "images/favicon.png"
  iconHeight = "35"
  iconWIdth = "35"

  [params.assets]
  disableFingerprinting = false
  favicon = "images/favicon.png"
  favicon16x16 = "images/favicon.png"
  favicon32x32 = "images/favicon-32x32.png"
  apple_touch_icon = "images/favicon.png"
  safari_pinned_tab = "images/favicon.png"

  [params.homepage]
  disableHeroSection = false
  heroTitle = "Alaska Regional Collaboration for Technology Innovation and Commercialization"
  heroDescription = "The Alaska Regional Collaboration for Technology Innovation and Commercialization (ARCTIC) program is an Office of Naval (ONR) program established in 2017 in support of Navy’s needs for public-private partnerships promoting commerce and collaboration between Alaska and the Arctic and Pacific regions, centered around energy and resiliency research. ARCTIC was highlighted in the Navy’s 2021 Blue Arctic strategy as an investment in building public-private partnerships and innovative solutions to help transform operating abilities and regional understanding for Naval forces."
  heroCTAPrimaryText = "Learn More"
  heroCTAPrimaryUrl = "/about/"
  heroCTASecondaryText = "Partners"
  heroCTASecondaryUrl = "/partners/"
  heroBackgroundImage = "images/2019summit-bruno_a1s.jpeg"
  heroLogo = "images/arctic-logo.png"
  seeMoreText = "More Posts"
  disableAboutSection = true
  aboutTitle = "The ARCTIC Program"
  aboutDescription = "An Office of Naval Research initiative"
  aboutImgUrl = "images/arctic-program.webp"
  aboutContent = "The Alaska Regional Collaboration for Technology Innovation and Commercialization (ARCTIC) is a collaboration designed to promote commerce and partnerships between Alaska and the Arctic and Pacific regions through advancements in energy through resiliency research, technology development/deployment and education."

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = "0"
  distance = "1000"
  threshold = "0.4"
  minMatchCharLength = "0"
  keys = [ "title", "permalink", "summary", "content" ]

[[params.plugins.css]]
link = "plugins/css/pico.min.css"

[[params.plugins.js]]
link = "plugins/js/feather.min.js"

[[menus.main]]
name = "Home"
title = "Home"
pre = "home"
url = "/"
weight = "10"

[[menus.main]]
name = "About"
title = "About"
pre = "info"
url = "/about"
weight = "20"

[[menus.main]]
name = "Partners"
title = "Partners"
pre = "users"
url = "/partners"
weight = "30"

[[menus.main]]
name = "Search"
title = "Search"
pre = "search"
url = "/search"
weight = "50"

[[menus.search]]
name = "Partners"
title = "Partners"
url = "/partners"
weight = "10"

[[menus.search]]
name = "Tags"
title = "Tags"
url = "/tags"
weight = "30"

[taxonomies]
  tag = "tags"