baseURL = "https://acep-uaf.github.io/the-arctic-program/"
languageCode = 'en-us'
title = 'The ARCTIC Program'
theme = 'piko'
paginate = "6"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true

[minify.tdewolff.html]
keepWhitespace = false

[params]
env = "development"
author = ""
description = "Website for the ARCTIC Program"
math = false
images = [""]
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowRelated = true
CookieNotice = ""
CookieLink = ""
CookieButton = ""
disableAnchoredHeadings = false
ShowReadingTime = false
ShowBreadCrumbs = true
showTOC = false
contactEmail = "UA-arctic-program-contact@alaska.edu"
relativeURLs = true

[params.footer]
aboutThisSite = "ARCTIC Program is an Office of Naval Research (ONR) initiative. Alaska develops economic capacity to ensure a sustainable future for Alaskans and shares Alaska-developed talent and technology with the global community."
generalAcknowledgement = "Website Management by [UAF ACEP](https://www.uaf.edu/acep/) | Website template by [Heksagon](https://github.com/heksagonnet/piko)"
onrAcknowledgement = "The Alaska Regional Collaboration for Technology Innovation and Commercialization (ARCTIC) program was or is sponsored by the Department of the Navy, Office of Naval Research under ONR award number(s) N00014-19-1-2235, N00014-22-1-2049, N00014-24-1-2675. Any opinions, findings, conclusions, or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the Office of Naval Research."

[[params.footer.logos]]
logo = "images/logos/ACEP-logo.png"
alt = "ACEP Logo"
websiteUrl = "https://www.uaf.edu/acep/"

[[params.footer.logos]]
logo = "images/logos/ONR-logo.png"
alt = "Office of Naval Research Logo"
websiteUrl = "https://www.onr.navy.mil/"

[[params.footer.logos]]
logo = "images/logos/UAF-navy.png"
alt = "University of Alaska Fairbanks Logo"
websiteUrl = "https://www.uaf.edu/uaf/"


[params.label]
title = "ARCTIC Program"
text = "Welcome to the ARCTIC Program"
lightNavIcon = "images/logos/arctic-favicon.png"
darkNavIcon = "images/logos/arctic-favicon.png"
iconHeight = "35"
iconWIdth = "35"

[params.assets]
disableFingerprinting = false
favicon = "images/logos/arctic-favicon.png"
favicon16x16 = "images/logos/arctic-favicon.png"
favicon32x32 = "images/logos/favicon-32x32.png"
apple_touch_icon = "images/logos/arctic-favicon.png"
safari_pinned_tab = "images/logos/arctic-favicon.png"
footerLogo = "images/logos/arctic-program.png"

[params.plugins]
[[params.plugins.css]]
link = "plugins/css/pico.min.css"

[[params.plugins.js]]
link = "plugins/js/feather.min.js"

[[menus.main]]
name = "Home"
title = "Home"
pre = "home"
url = "/"
weight = "10"

[[menus.main]]
name = "About"
title = "About"
pre = "info"
url = "/about"
weight = "20"

[[menus.main]]
name = "Activities"
title = "Activities"
pre = "activity"
url = "/foundationalActivities"
weight = "30"

[[menus.main]]
name = "Partners"
title = "Partners"
pre = "users"
url = "/partners"
weight = "40"

[[menus.main]]
name = "Contact"
title = "Contact"
pre = "mail"
url = "mailto:UA-arctic-program-contact@alaska.edu"
weight = "50"

[module]
[[module.mounts]]
source = 'node_modules'
target = 'assets'
[[module.mounts]]
source = 'assets'
target = 'assets'
