baseURL = "https://acep-uaf.github.io/the-arctic-program/"
languageCode = 'en-us'
title = 'The ARCTIC Program'
theme = 'piko'
paginate = "6"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true

[minify.tdewolff.html]
keepWhitespace = false

[params]
env = "development"
author = ""
description = "Website for the ARCTIC Program"
math = false
images = ["/uploads/og.webp"]
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowRelated = true
CookieNotice = "We use cookies to improve your experience on our site and to show you relevant advertising."
CookieLink = "/legal/privacy/#cookies-and-web-beacons"
CookieButton = "Cookies Policy"
disableAnchoredHeadings = false
ShowReadingTime = false
ShowBreadCrumbs = true
showTOC = false
contactEmail = "UA-arctic-program-contact@alaska.edu"
footerAcknowledgement = "Website Management by [UAF ACEP](https://www.uaf.edu/acep/) | Website template by [Heksagon](https://github.com/heksagonnet/piko)"
relativeURLs = true

[params.label]
title = "ARCTIC Program"
text = "Welcome to the ARCTIC Program"
lightNavIcon = "images/logos/arctic-favicon.png"
darkNavIcon = "images/logos/arctic-favicon.png"
iconHeight = "35"
iconWIdth = "35"

[params.assets]
disableFingerprinting = false
favicon = "images/logos/arctic-favicon.png"
favicon16x16 = "images/logos/arctic-favicon.png"
favicon32x32 = "images/logos/favicon-32x32.png"
apple_touch_icon = "images/logos/arctic-favicon.png"
safari_pinned_tab = "images/logos/arctic-favicon.png"
footerLogo = "images/logos/arctic-program.png"

# Search
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = "0"
distance = "1000"
threshold = "0.4"
minMatchCharLength = "0"
keys = ["title", "permalink", "summary", "content"]

[params.plugins]
[[params.plugins.css]]
link = "plugins/css/pico.min.css"

[[params.plugins.js]]
link = "plugins/js/feather.min.js"

[[menus.main]]
name = "Home"
title = "Home"
pre = "home"
url = "/"
weight = "10"

[[menus.main]]
name = "About"
title = "About"
pre = "info"
url = "/about"
weight = "20"

[[menus.main]]
name = "Activities"
title = "Activities"
pre = "activity"
url = "/foundationalActivities"
weight = "30"

[[menus.main]]
name = "Partners"
title = "Partners"
pre = "users"
url = "/partners"
weight = "40"

[[menus.main]]
name = "Contact"
title = "Contact"
pre = "mail"
url = "mailto:UA-arctic-program-contact@alaska.edu"
weight = "50"

[[menus.main]]
name = "Search"
title = "Search"
pre = "search"
url = "/search"
weight = "60"

[[menus.search]]
name = "Partners"
title = "Partners"
url = "/partners"
weight = "10"

[[menus.search]]
name = "Foundational Activities"
title = "Foundational Activities"
url = "/foundationalActivities"
weight = "20"

[module]
[[module.mounts]]
source = 'node_modules'
target = 'assets'
[[module.mounts]]
source = 'assets'
target = 'assets'
