baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Arctic Program'
theme = 'piko'
paginate = "6"
copyright = 'A template by [Heksagon](https://www.heksagon.net "Your most friendly developer")'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true

[minify.tdewolff.html]
keepWhitespace = false

[params]
env = "production"
author = ""
description = "Your website description"
math = false
images = [ "/uploads/og.webp" ]
comments = true
mainSections = [ "blog" ]
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowRelated = true
CookieNotice = "We use cookies to improve your experience on our site and to show you relevant advertising."
CookieLink = "/legal/privacy/#cookies-and-web-beacons"
CookieButton = "Cookies Policy"
disableAnchoredHeadings = false
ShowReadingTime = false
ShowBreadCrumbs = true
showTOC = true

[params.analytics.google]

[params.analytics.yandex]

[params.analytics.bing]

  [params.label]
  title = "_Arctic Program_"
  text = "Welcome to the Artic Program"
  lightNavIcon = "/images/arctic-logo.png"
  darkNavIcon = "/images/arctic-logo.png"
  iconHeight = "35"
  iconWIdth = "35"

  [params.assets]
  disableFingerprinting = false
  favicon = "/images/arctic-logo.png"
  favicon16x16 = "/images/arctic-logo.png"
  favicon32x32 = "/images/arctic-logo.png"
  apple_touch_icon = "/images/arctic-logo.png"
  safari_pinned_tab = "/images/arctic-logo.png"

  [params.homepage]
  disableHeroSection = false
  heroTitle = "ARCTIC Program"
  heroDescription = "The Alaska Regional Collaboration for Technology Innovation and Commercialization (ARCTIC) is a collaboration designed to promote commerce and partnerships between Alaska and the Arctic and Pacific regions through advancements in energy through resiliency research, technology development/deployment and education."
  heroCTAPrimaryText = "Learn More"
  heroCTAPrimaryUrl = "/about/"
  heroCTASecondaryText = "Partners"
  heroCTASecondaryUrl = "/partners/"
  heroBackgroundImage = ""
  heroLogo = "/images/arctic-logo.png"
  seeMoreText = "More Posts"
  disableAboutSection = false
  aboutTitle = "The ARCTIC Program"
  aboutDescription = "An Office of Naval Research initiative"
  aboutImgUrl = "/uploads/self.webp"
  aboutContent = "The Alaska Regional Collaboration for Technology Innovation and Commercialization (ARCTIC) is a collaboration designed to promote commerce and partnerships between Alaska and the Arctic and Pacific regions through advancements in energy through resiliency research, technology development/deployment and education."
  disablePartnerSection = false
  portfolioTitle = "Participating Partners"
  portfolioDescription = ""

    [[params.homepage.portfolio]]
    imageUrl = "/images/acep-logo-sm.png"
    alt = "ACEP Alaska Center for Energy and Power"
    description = "Developing practical, cost-effective energy solutions for Alaska and beyond"
    websiteUrl = "https://acep.uaf.edu"

    [[params.homepage.portfolio]]
    imageUrl = "/images/bei-logo-sm.png"
    alt = "UAA Business Enterprise Institute"
    description = "Supporting business and entrepreneurial capacities across Alaska by linking economic development programs"
    websiteUrl = "https://www.uaa.alaska.edu/academics/business-enterprise-institute"

    [[params.homepage.portfolio]]
    imageUrl = "/images/centerice-logo-sm.png"
    alt = "Alaska Center ICE"
    description = "Supporting the commercialization & deployment of new technology"
    websiteUrl = "https://www.uaf.edu/centerice"

    [[params.homepage.portfolio]]
    imageUrl = "/images/launchalaska-logo-sm.png"
    alt = "Launch Alaska"
    description = "Accelerating the Resource Revolution"
    websiteUrl = "https://www.launchalaska.com"

    [[params.homepage.portfolio]]
    imageUrl = "/images/reap-logo-sm.png"
    alt = "REAP Renewable Energy Alaska Project"
    description = "Advancing Clean Energy in Alaska"
    websiteUrl = "https://alaskarenewableenergy.org"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = "0"
  distance = "1000"
  threshold = "0.4"
  minMatchCharLength = "0"
  keys = [ "title", "permalink", "summary", "content" ]

[[params.plugins.css]]
link = "plugins/css/pico.min.css"

[[params.plugins.js]]
link = "plugins/js/feather.min.js"

[[menus.main]]
name = "Home"
title = "Home"
pre = "home"
url = "/"
weight = "10"

[[menus.main]]
name = "About"
title = "About"
pre = "info"
url = "/about"
weight = "20"

[[menus.main]]
name = "Partners"
title = "Partners"
pre = "users"
url = "/partners"
weight = "30"

[[menus.main]]
name = "Search"
title = "Search"
pre = "search"
url = "/search"
weight = "50"

[[menus.main]]
name = "Github"
pre = "github"
url = "https://github.com/heksagonnet/piko"
weight = "60"

[[menus.search]]
name = "Categories"
title = "Categories"
url = "/categories"
weight = "10"

[[menus.search]]
name = "Archives"
title = "Archives"
url = "/archives"
weight = "20"

[[menus.search]]
name = "Tags"
title = "Tags"
url = "/tags"
weight = "30"

[taxonomies]
  tag = "tags"